### ISSUE TITLE
Cannot use aliased module as value for option `using: ...`

### ISSUE THREAD

**Issue by nicooga** [elixir-maru/maru_entity#10]
When trying to use an aliased module as the value for the `using` option in `expose :attribute, using: ...`, I've got this compile time error:
~~~elixir
defmodule MyCompany.API.Public.Entities.Listing do
  # ...
  alias MyCompany.API.Public.Entities
  expose :show_location,
    [using: Entities.Location],
    fn(l, _options)-> show_location(l) end
~~~
```
== Compilation error in file lib/my_company/api/public/entities/listing.ex ==
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("Elixir.Entities.Location", :utf8)
    (elixir) src/elixir_aliases.erl:119: :elixir_aliases.safe_concat/1
    (maru_entity) lib/maru/entity.ex:168: Maru.Entity.do_parse/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (maru_entity) lib/maru/entity.ex:109: Maru.Entity.parse/1
    lib/my_company/api/public/entities/listing.ex:31: (module)
```
I've made an example project to reproduce the error. I don't get a compile error there though, but a run time error saying `function Cat.__exposures__/0 is undefined`:

~~~elixir
defmodule MaruErrorExample.House do
  use Maru.Entity
  alias MaruErrorExample.Animals.Cat

  expose :dog, using: MaruErrorExample.Animals.Dog
  expose :cat, [using: Cat]
end

defmodule MaruErrorExample.Animals.Dog do
  use Maru.Entity
  expose :color
end

defmodule MaruErrorExample.Animals.Cat do
  use Maru.Entity
  expose :color
end
~~~
I can imagine that since `expose/3` is a macro, the aliased module name is passed as an AST, and evaluated  as a plain module name, not an aliased one. Not sure about how would I fix this. I'd expect the whole expanded module name to be passed to `expose/3` but that is not happening.

**Comment by falood** [comment]
thank you for pointing it out, I think it a bug [here](https://github.com/elixir-maru/maru_entity/blob/master/lib/maru/entity.ex#L248-L251) should make alias modules works

**Comment by nicooga** [comment]
I think this should fix the error:

~~~elixir
case Keyword.get(options, :using, nil) do
  nil -> nil
  {:__aliases__, [alias: false], module} ->
    %Serializer{module: Module.safe_concat(module), type: :one}
  {:__aliases__, [alias: module], _} ->
    %Serializer{module: Module.safe_concat(module), type: :one}
end
~~~
Tomorrow morning I can work on the fix if you don't have time for it.

**Comment by falood** [comment]
Maybe, we have to merge `alias modules` and `using module` for working with `alias A.B` and `using B.C` together 🙂 

that's great if you can help to do it, thanks! ❤️

**Comment by nicooga** [comment]
Not sure what you mean. Would my silly example `House -> Dog/Cat` be an acceptance test?

**Comment by falood** [comment]
sorry, my bad, I tested it again, your idea is totally correct. 
ignore my unnecessary concern 🙂

**Comment by nicooga** [comment]
Now that this is released we can close the issue. Thank you!
